### ISSUE TITLE
Status of spaceapi.net

### ISSUE THREAD

**Issue by abitrolly** [SpaceApi/website#100]
Looks like http://spaceapi.net/ is borked. Are there any plans to place a redirect to a new version?

I would only keep this page http://spaceapi.net/documentation somewhere around. The style is clean and usability is better than current https://spaceapi.io/docs/

**Comment by dbrgn** [comment]
We don't have control over spaceapi.net anymore. The page at spaceapi.io should be up to date.

Improvements in styling would be welcome! Sources are all in this repository.

**Comment by abitrolly** [comment]
@dbrgn interesting.. What is the whole story?

**Comment by dbrgn** [comment]
We couldn't reach the previous maintainer anymore, and he still has control over the domain. So we started maintaining the project ourselves and signed up for a new domain :slightly_smiling_face: There are also some more details here: https://spaceapi.io/spaceapi-history/

**Comment by abitrolly** [comment]
@dbrgn are there any credits for that person? The history doesn't mention anyone in particular, and why the person is unreachable. The domain is prolonged every years, so I guess the person is still alive.

**Comment by dbrgn** [comment]
Yes, it's slopjong. The SpaceAPI was his idea and he developed a lot of great tooling around it. We (me, @rnestler and @gidsi) didn't want to let the project die, so we started to maintain it (initially together with slopjong). Unfortunately, he hasn't reacted to contact attempts for years now. (That's OK though, of course, priorities shift.)

**Comment by abitrolly** [comment]
Is `slopjong` on GitHub? Maybe something happened to him offline?

**Comment by dbrgn** [comment]
No, as far as I know he seems to receive messages, just doesn't react to them. I'm not sure why, but again, that's perfectly OK and I don't want to bother him if he doesn't want to reply.

**Comment by abitrolly** [comment]
@dbrgn well, people ability to respond to messages are affected by daily jobs and duties. Sometimes people don't speak, because of conflicts, and that's a major challenges when building a hackerspace. That could be an interesting topic for CCC.
