### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by zeno4ever** [SpaceApi/website#113]
When acces https://spaceapi.io website I get a ERR_CERT_REVOKED error.

spaceapi.io is one of the sites that have to (manually) renew certificate, see Lets Encrypt blog on :
https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449

**Comment by dbrgn** [comment]
It seems so 😕

@gidsi any idea how to do that with Traefik? Can we just delete the current certs?

**Comment by dbrgn** [comment]
Ah: https://community.letsencrypt.org/t/early-renewal-traefik/170567

> It's not hard, just empty the array inside your acme.json and restart Traefik it will do the rest.

**Comment by gidsi** [comment]
@dbrgn it seems to be fixed, is there a reason you left the issue open?

**Comment by dbrgn** [comment]
@gidsi no, I still get SEC_ERROR_REVOKED_CERTIFICATE when connecting. I left it open because yesterday I didn't find the time to fix it. (If you don't have time, I can try to do it tonight...)

**Comment by dbrgn** [comment]
The `acme.json` is at `/srv/docker/traefik/acme/`.

I made a backup of the `acme.json` (`acme.json.bak-20220201`), then removed all entries in the `Certificates` array. Then I called `docker restart traefik_reverseproxy_1`. Now I get this error 🙈 

> Secure Connection Failed
> 
> An error occurred during a connection to spaceapi.io. Peer reports it experienced an internal error.
> 
> Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

**Comment by dbrgn** [comment]
Ah, it probably took a while to fetch all certificates. It's back up now. 🎉
