### ISSUE TITLE
New MyHackerspace App

### ISSUE THREAD

**Issue by niccokunzmann** [SpaceApi/website#119]
The new app my-hackerspace is hosted here: https://github.com/spaceapi-community/my-hackerspace/
and it available on f-droid: https://f-droid.org/repository/browse/?fdid=io.spaceapi.community.myhackerspace
I created this issue: https://github.com/spaceapi-community/my-hackerspace/issues/13

The question for me is: should the old/unmaintained app be still listed next to the new one or should the entry be modified to just show the new app?

**Comment by dbrgn** [comment]
It should be updated. Please give us some time to finish the migration path for the users 🙂 https://github.com/fixme-lausanne/MyHackerspace/pull/88

**Comment by niccokunzmann** [comment]
@dbrgn thanks and happy to watch and help!
