### ISSUE TITLE
Add repository for simple micropython + PHP endpoint

### ISSUE THREAD

**Issue by jhaand** [SpaceApi/website#123]
When I look at the possibilities to provide an endpoint, I see quite some exotic choices and it doesn't provide the sensor + edge component
I created the implementation for an endpoint using NodeMCU, microPython and PHP on any server you like. It's very simple to get started. We used it during the Hacker Hotel event. See [this](https://mas.to/@jhaand/109833789261363819) post.

I would like this repository to be added to the 'provide Endpoint' page. It allows people to get started quite easily and then apply to spaceapi.io to get their endpoint in the directory. 

You can find it here:
https://gitlab.com/jhaand/hacker-hotel-space-state

**Comment by dbrgn** [comment]
Nice! Would you like to submit a pull request? There are instructions in the README: https://github.com/SpaceApi/website#adding-an-applibrarytool-aka-stuff

**Comment by jhaand** [comment]
Great. I will look into it.

**Comment by jhaand** [comment]
I made the changes and you see them in the above pull request.

**Comment by jhaand** [comment]
This issue has been resolved with the above mentioned PR. 
Thank you very much for including this.
