### ISSUE TITLE
Add favicon to website

### ISSUE THREAD

**Issue by dbrgn** [SpaceApi/website#15]
It can be found here: https://github.com/SpaceApi/website/blob/master/logo/favicon.ico

**Comment by TheWebTech** [comment]
it appears someone already implemented this but your site hasn't been updated with the new file
https://github.com/SpaceApi/website/blob/9df207c610303d173c40ea61b49c57f018011bb6/theme/templates/base.html#L14

**Comment by radharay** [comment]
<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">     
<link rel="icon" href="../favicon.ico" type="image/x-icon">

**Comment by dbrgn** [comment]
@TheWebTech I should have mentioned this, the icon simply needs to be put at the correct static file location for [Pelican](http://docs.getpelican.com/) :slightly_smiling_face: I'll add a note to the PR.

**Comment by EkaanshArora** [comment]
@dbrgn check if PR #18 works.

**Comment by dbrgn** [comment]
@EkaanshArora it does not, the file has not been copied to the correct location. see instructions at https://github.com/SpaceApi/website/pull/16.

**Comment by EkaanshArora** [comment]
@dbrgn Apologies, I think I made the required changes in the next commit.
