### ISSUE TITLE
Add section about implementations

### ISSUE THREAD

**Issue by rnestler** [SpaceApi/website#23]
It would be good to have a list of SpaceAPI implementations in different programming languages. Probably in some kind of table:

|language|repository|
|------------|-------------|
|Python|https://github.com/|

**Comment by astro** [comment]
Additional columns in this table that could be useful:
- data sources
- backends

**Comment by dbrgn** [comment]
What's an "implementation"? Isn't this what https://spaceapi.io/pages/apps.html is for?

Maybe we should restructure and group this page.

**Comment by dbrgn** [comment]
What about using separate files with metadata, and combining them to a single page where you can filter by category / tags?

Not sure how that can be done with Pelican, but I'm sure there's a way.

**Comment by gidsi** [comment]
> > What's an "implementation"? Isn't this what https://spaceapi.io/pages/apps.html is for?
> I meant like language bindings. So just libraries which enables you to write an app basically.

I think https://spaceapi.io/write-software/ might solve the problem. If so i would like to close this issue :)

**Comment by dbrgn** [comment]
I agree :slightly_smiling_face:
