### ISSUE TITLE
Document API requirements

### ISSUE THREAD

**Issue by dbrgn** [SpaceApi/website#3]
API endpoints should return a HTTP200 status code. Furthermore, they should set the `Access-Control-Allow-Origin: *` header.

**Comment by dns2utf8** [comment]
Security: Must not enable `jsonp`

**Comment by dbrgn** [comment]
@dns2utf8 What exactly do you mean with that?

**Comment by dns2utf8** [comment]
A JSONp endpoint has some [security problems](https://security.stackexchange.com/questions/23438/security-risks-with-jsonp)

**Comment by dbrgn** [comment]
Well yes, if you use JSONP to load a SpaceAPI endpoint, then that endpoint can inject code into your page. But that's the point of using JSONP :)

In any case, can one even prevent the use of the JSONP technique as server operator?

**Comment by gidsi** [comment]
Added by #30
