### ISSUE TITLE
Warn when using HTTP link to schema with the validator (is HTTPS-only)?

### ISSUE THREAD

**Issue by CRImier** [SpaceApi/website#36]
After doing a PR to the schema repo recently, it turned out that the validator doesn't accept HTTP pages even if CORS is enabled. Would be helpful to let the user know somehow - either detect "http://" in the URL and show a debugging message, or at least add a "Are you using HTTP? It might not work due to mixed-content policy" note to the debug log entry that is shown when the fetch fails (one that tells you about CORS).  I've seen the "use debug console" suggestion in other issue, but the validator itself doesn't tell you that you can use it as a debugging tool - at the very least, a note about that would be helpful.

**Comment by dbrgn** [comment]
@CRImier yep, you're right, the validator definitely needs some love.

**Comment by CRImier** [comment]
"some love" sounds kinda high-effort, however, just adding a couple more debugging entries shouldn't be hard - will look into it if I have time by the end of the week =)

**Comment by dbrgn** [comment]
No, actually this should be fairly simple to improve the reporting of the validator. You can find the HTML code at https://github.com/SpaceApi/website/blob/master/content/pages/validator.md and the JS at https://github.com/SpaceApi/website/blob/master/content/js/validator.js. It's really just a very hacky early draft that we never finished.

If you'd like to revamp it a bit, feel free to remove / replace the code as you want. We're not attached to it.

**Comment by rnestler** [comment]
We could probably do the validation completely server side. But this would need changes in the validator to accept URLs: https://github.com/SpaceApi/validator
